name: ci

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  push_to_registry:
    name: CI-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 这个步骤会生成多个平台的镜像
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/huaxiexiyan-web-erp:main
          # 缓存配置
          cache-from: type=gha
          cache-to: type=gha,mode=min
